<script lang="ts">
  import type { Data } from "../lib/transform";
  import { fmtTokens, fmtCost } from "../lib/format";
  import Tooltip from "./Tooltip.svelte";

  const COLORS = ["#6366f1","#f59e0b","#ef4444","#10b981","#8b5cf6","#ec4899","#14b8a6","#f97316"];

  let { data }: { data: Data } = $props();
  let tools = $derived(data.aiTools);
  let activeTool = $state(0);
  let current = $derived(tools[activeTool]);
  let modelEntries = $derived(
    current ? Object.entries(current.model_breakdown).sort((a, b) => b[1] - a[1]) : []
  );
  let totalModelMsgs = $derived(modelEntries.reduce((n, [, v]) => n + v, 0));
</script>

<section class="rounded-xl border border-stone-200 dark:border-stone-800 bg-stone-50 dark:bg-stone-900 shadow-sm dark:shadow-stone-950/30 p-5">
  <div class="flex items-baseline gap-3 mb-5">
    <Tooltip text="AI activity parsed from your local session files (pi, claude-code). Aggregated per session — each row is one conversation.">
      <h3 class="font-display text-lg text-stone-900 dark:text-stone-100">AI Sessions</h3>
    </Tooltip>
    <div class="ml-auto">
      {#if tools.length > 1}
        <div class="inline-flex rounded-lg bg-stone-100 dark:bg-stone-800 p-0.5">
          {#each tools as t, i}
            <button
              class="px-3 py-1 text-xs font-medium rounded-md transition-colors {activeTool === i ? 'bg-stone-50 dark:bg-stone-700 text-stone-900 dark:text-stone-100 shadow-sm' : 'text-stone-500 hover:text-stone-700'}"
              onclick={() => (activeTool = i)}
            >{t.tool}</button>
          {/each}
        </div>
      {:else if tools.length === 1}
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-mono bg-indigo-50 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300 ring-1 ring-indigo-200 dark:ring-indigo-800">{tools[0].tool}</span>
      {/if}
    </div>
  </div>

  {#if current}
    <!-- Stat cards -->
    <div class="grid grid-cols-4 gap-3 mb-5 max-md:grid-cols-2">
      {#each [
        { label: "Sessions", value: String(current.session_count), sub: `${current.message_count} msgs`,
          tip: "Number of distinct AI conversation sessions. Each session = one JSONL file in the tool's sessions directory." },
        { label: "Input", value: fmtTokens(current.total_input), sub: "tokens",
          tip: "Total input tokens including cache reads. These are tokens the model reads from your prompt and conversation history." },
        { label: "Output", value: fmtTokens(current.total_output), sub: "tokens",
          tip: "Total output tokens generated by the model. Higher output = more code/text written by the AI." },
        { label: "Cost", value: fmtCost(current.total_cost), sub: current.total_cache > 0 ? `${fmtTokens(current.total_cache)} cached` : "total",
          tip: current.total_cost > 0
            ? "Estimated API cost. Cache reads/writes are cheaper than fresh input — the 'cached' count shows how much was served from cache."
            : "Cost not available — this CLI tool doesn't expose pricing in its session files." },
      ] as stat}
        <div class="rounded-lg bg-stone-50 dark:bg-stone-800/50 border border-stone-100 dark:border-stone-800 p-4 text-center">
          <Tooltip text={stat.tip} position="bottom">
            <div class="uppercase tracking-widest text-[10px] font-mono text-stone-400 mb-1.5">{stat.label}</div>
          </Tooltip>
          <div class="font-display text-2xl text-stone-900 dark:text-stone-100 tabular-nums">{stat.value}</div>
          <div class="text-[10px] text-stone-400 font-mono mt-0.5">{stat.sub}</div>
        </div>
      {/each}
    </div>

    <!-- Model breakdown -->
    {#if modelEntries.length > 0}
      <div class="mb-5">
        <Tooltip text="Which AI models were used across all sessions, by message count. One session can switch models mid-conversation.">
          <div class="uppercase tracking-widest text-[10px] font-mono text-stone-400 mb-3">Models</div>
        </Tooltip>
        <div class="flex h-2 rounded-full overflow-hidden bg-stone-100 dark:bg-stone-800 mb-3">
          {#each modelEntries as [, count], i}
            <span class="block h-full" style:flex={count} style:background={COLORS[i % COLORS.length]}></span>
          {/each}
        </div>
        <div class="flex flex-wrap gap-x-4 gap-y-1">
          {#each modelEntries as [model, count], i}
            <span class="flex items-center gap-1.5 text-[11px]">
              <span class="w-2 h-2 rounded-sm" style:background={COLORS[i % COLORS.length]}></span>
              <span class="font-mono text-stone-600 dark:text-stone-300">{model}</span>
              <span class="font-mono text-stone-400 tabular-nums">{Math.round((count / totalModelMsgs) * 100)}%</span>
            </span>
          {/each}
        </div>
      </div>
    {/if}

    <!-- Top model -->
    {#if current.top_model}
      <div class="flex items-center gap-2 mb-4 py-2 px-3 rounded-lg bg-indigo-50 dark:bg-indigo-950/50 border border-indigo-100 dark:border-indigo-900">
        <span class="uppercase tracking-widest text-[10px] font-mono text-indigo-600 dark:text-indigo-400">Primary</span>
        <span class="font-mono text-sm text-stone-700 dark:text-stone-300">{current.top_model}</span>
      </div>
    {/if}

    <!-- Session table -->
    {#if current.sessions.length > 0}
      <div class="max-h-[320px] overflow-y-auto">
        <table class="w-full text-xs">
          <thead class="sticky top-0 bg-stone-50 dark:bg-stone-900 z-10">
            <tr class="border-b border-stone-100 dark:border-stone-800">
              {#each ["Time", "Project", "Model", "Msgs", "Tokens", "Cost"] as col, i}
                <th class="py-2 px-1.5 uppercase tracking-widest text-[10px] font-mono text-stone-400 font-medium {i >= 3 ? 'text-right' : 'text-left'}">{col}</th>
              {/each}
            </tr>
          </thead>
          <tbody>
            {#each current.sessions as sess}
              <tr class="border-b border-stone-50 dark:border-stone-800/50 last:border-0 hover:bg-stone-50 dark:hover:bg-stone-800/30 transition-colors">
                <td class="py-2 px-1.5 font-mono tabular-nums text-stone-500">{sess.start_time}–{sess.end_time}</td>
                <td class="py-2 px-1.5 text-stone-700 dark:text-stone-300 font-medium">{sess.project || "—"}</td>
                <td class="py-2 px-1.5 font-mono text-[10px] text-stone-400">{sess.model || "—"}</td>
                <td class="py-2 px-1.5 font-mono tabular-nums text-stone-500 text-right">{sess.message_count}</td>
                <td class="py-2 px-1.5 font-mono tabular-nums text-stone-500 text-right">{fmtTokens(sess.total_input + sess.total_output)}</td>
                <td class="py-2 px-1.5 font-mono tabular-nums text-stone-500 text-right">{fmtCost(sess.total_cost)}</td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {/if}

    {#if data.aiRecap}
      <div class="mt-5 pt-4 border-t border-stone-100 dark:border-stone-800">
        <div class="uppercase tracking-widest text-[10px] font-mono text-stone-400 mb-2">AI Recap</div>
        <p class="text-xs text-stone-600 dark:text-stone-300 leading-relaxed bg-indigo-50 dark:bg-indigo-950/30 border-l-2 border-indigo-500 py-2.5 px-3.5 rounded-r-md whitespace-pre-wrap">{data.aiRecap}</p>
      </div>
    {/if}
  {/if}
</section>
