<script lang="ts">
  import type { Data } from "../lib/transform";

  let { data }: { data: Data } = $props();

  let text = $derived(data.standup);
  let isAI = $derived(data.standupIsAI);

  // Split into lines and render bullet points nicely.
  let lines = $derived(
    (text ?? "")
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.length > 0)
  );
</script>

{#if text}
  <section
    class="rounded-xl border border-indigo-100 dark:border-indigo-900/60
           bg-indigo-50/60 dark:bg-indigo-950/30 shadow-sm p-5"
  >
    <div class="flex items-center gap-2 mb-3">
      <h3 class="font-display text-base text-stone-900 dark:text-stone-100">
        Today's standup
      </h3>
      {#if isAI}
        <span
          class="px-1.5 py-0.5 rounded text-[10px] font-mono uppercase tracking-wide
                 bg-indigo-100 dark:bg-indigo-900 text-indigo-600 dark:text-indigo-400"
          title="Generated by your configured AI command"
        >AI</span>
      {/if}
      <span class="ml-auto text-[11px] font-mono text-stone-400">
        today &amp; yesterday
      </span>
    </div>

    <div class="space-y-1">
      {#each lines as line}
        {#if line.startsWith("## ")}
          <p class="text-[11px] font-mono uppercase tracking-widest text-stone-400 pt-2 first:pt-0">
            {line.slice(3)}
          </p>
        {:else if line.startsWith("### ")}
          <p class="text-sm font-semibold text-stone-700 dark:text-stone-300 pt-1.5">
            {line.slice(4)}
          </p>
        {:else if line.startsWith("- ")}
          <p class="flex gap-2 text-sm text-stone-700 dark:text-stone-300 leading-relaxed">
            <span class="text-indigo-400 shrink-0 mt-0.5">•</span>
            <span>{line.slice(2)}</span>
          </p>
        {:else if line.startsWith("  - ")}
          <p class="flex gap-2 text-xs text-stone-500 dark:text-stone-400 leading-relaxed pl-4">
            <span class="text-stone-300 dark:text-stone-600 shrink-0">·</span>
            <span>{line.slice(4)}</span>
          </p>
        {:else}
          <p class="text-sm text-stone-600 dark:text-stone-400 leading-relaxed">{line}</p>
        {/if}
      {/each}
    </div>
  </section>
{/if}
