export const mockData = {
  period: "week",
  generated: "Fri 01 May, 21:34",
  total_focus_min: 1279,
  total_blocks: 74,
  total_switches: 260,
  files_changed: 776,
  lines_added: 22895,
  lines_removed: 40051,
  by_project: {
    "7guis": 1,
    flowd: 367,
    mossfin: 3,
    "pi-mono": 30,
    setthemacup: 526,
    "wick-ui": 261,
    "wick-ui-v2": 27,
  },
  by_tool: {
    "2.1.123": 2,
    Python: 34,
    "[tmux]": 42,
    bash: 8,
    bun: 56,
    curl: 1,
    dev: 293,
    editor: 91,
    fastfetch: 1,
    fw: 11,
    git: 29,
    go: 1,
    lazygit: 22,
    node: 383,
    nvim: 213,
    other: 76,
    runtime: 6,
    sh: 1,
    shell: 9,
    test: 1,
    tmux: 1,
    vp: 3,
    yazi: 3,
    zsh: 91,
  },
  languages: {
    CSS: 28,
    Go: 0,
    HTML: 5,
    JSON: 25,
    JavaScript: 114,
    Markdown: 6,
    Shell: 0,
    TypeScript: 22,
    YAML: 4,
    db: 0,
    "db-shm": 0,
    "db-wal": 0,
    gitignore: 0,
    mdx: 3,
    other: 0,
    svg: 1,
    zshrc: 0,
  },
  heatmap: [
    {
      day: "Sat 25",
      hour: 0,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 1,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 2,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 3,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 4,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 5,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 6,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 7,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 8,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 9,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 10,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 11,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 12,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 13,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 14,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 15,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 16,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 17,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 18,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 19,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 20,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 21,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 22,
      minute: 0,
    },
    {
      day: "Sat 25",
      hour: 23,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 0,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 1,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 2,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 3,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 4,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 5,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 6,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 7,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 8,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 9,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 10,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 11,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 12,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 13,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 14,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 15,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 16,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 17,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 18,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 19,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 20,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 21,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 22,
      minute: 0,
    },
    {
      day: "Sun 26",
      hour: 23,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 0,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 1,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 2,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 3,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 4,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 5,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 6,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 7,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 8,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 9,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 10,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 11,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 12,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 13,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 14,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 15,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 16,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 17,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 18,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 19,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 20,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 21,
      minute: 0,
    },
    {
      day: "Mon 27",
      hour: 22,
      minute: 40,
    },
    {
      day: "Mon 27",
      hour: 23,
      minute: 57,
    },
    {
      day: "Tue 28",
      hour: 0,
      minute: 5,
    },
    {
      day: "Tue 28",
      hour: 1,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 2,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 3,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 4,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 5,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 6,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 7,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 8,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 9,
      minute: 4,
    },
    {
      day: "Tue 28",
      hour: 10,
      minute: 99,
    },
    {
      day: "Tue 28",
      hour: 11,
      minute: 100,
    },
    {
      day: "Tue 28",
      hour: 12,
      minute: 56,
    },
    {
      day: "Tue 28",
      hour: 13,
      minute: 72,
    },
    {
      day: "Tue 28",
      hour: 14,
      minute: 46,
    },
    {
      day: "Tue 28",
      hour: 15,
      minute: 56,
    },
    {
      day: "Tue 28",
      hour: 16,
      minute: 52,
    },
    {
      day: "Tue 28",
      hour: 17,
      minute: 17,
    },
    {
      day: "Tue 28",
      hour: 18,
      minute: 10,
    },
    {
      day: "Tue 28",
      hour: 19,
      minute: 0,
    },
    {
      day: "Tue 28",
      hour: 20,
      minute: 19,
    },
    {
      day: "Tue 28",
      hour: 21,
      minute: 59,
    },
    {
      day: "Tue 28",
      hour: 22,
      minute: 4,
    },
    {
      day: "Tue 28",
      hour: 23,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 0,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 1,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 2,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 3,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 4,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 5,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 6,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 7,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 8,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 9,
      minute: 30,
    },
    {
      day: "Wed 29",
      hour: 10,
      minute: 18,
    },
    {
      day: "Wed 29",
      hour: 11,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 12,
      minute: 38,
    },
    {
      day: "Wed 29",
      hour: 13,
      minute: 18,
    },
    {
      day: "Wed 29",
      hour: 14,
      minute: 24,
    },
    {
      day: "Wed 29",
      hour: 15,
      minute: 19,
    },
    {
      day: "Wed 29",
      hour: 16,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 17,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 18,
      minute: 4,
    },
    {
      day: "Wed 29",
      hour: 19,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 20,
      minute: 18,
    },
    {
      day: "Wed 29",
      hour: 21,
      minute: 2,
    },
    {
      day: "Wed 29",
      hour: 22,
      minute: 0,
    },
    {
      day: "Wed 29",
      hour: 23,
      minute: 10,
    },
    {
      day: "Thu 30",
      hour: 0,
      minute: 43,
    },
    {
      day: "Thu 30",
      hour: 1,
      minute: 52,
    },
    {
      day: "Thu 30",
      hour: 2,
      minute: 16,
    },
    {
      day: "Thu 30",
      hour: 3,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 4,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 5,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 6,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 7,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 8,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 9,
      minute: 4,
    },
    {
      day: "Thu 30",
      hour: 10,
      minute: 39,
    },
    {
      day: "Thu 30",
      hour: 11,
      minute: 5,
    },
    {
      day: "Thu 30",
      hour: 12,
      minute: 3,
    },
    {
      day: "Thu 30",
      hour: 13,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 14,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 15,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 16,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 17,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 18,
      minute: 30,
    },
    {
      day: "Thu 30",
      hour: 19,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 20,
      minute: 30,
    },
    {
      day: "Thu 30",
      hour: 21,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 22,
      minute: 0,
    },
    {
      day: "Thu 30",
      hour: 23,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 0,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 1,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 2,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 3,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 4,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 5,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 6,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 7,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 8,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 9,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 10,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 11,
      minute: 30,
    },
    {
      day: "Fri 01",
      hour: 12,
      minute: 60,
    },
    {
      day: "Fri 01",
      hour: 13,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 14,
      minute: 30,
    },
    {
      day: "Fri 01",
      hour: 15,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 16,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 17,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 18,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 19,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 20,
      minute: 60,
    },
    {
      day: "Fri 01",
      hour: 21,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 22,
      minute: 0,
    },
    {
      day: "Fri 01",
      hour: 23,
      minute: 0,
    },
  ],
  timeline: [
    {
      start: "22:00",
      end: "22:30",
      repo: "flowd",
      branch: "main",
      focus: 14,
      switches: 23,
    },
    {
      start: "22:30",
      end: "23:00",
      repo: "flowd",
      branch: "main",
      focus: 26,
      switches: 17,
      ai: 'Fixed fw module bugs and added platform detection logic (+298/-67 across 12 files). High switch count (17) with most time in "other" tools suggests heavy reading/research alongside code changes.',
    },
    {
      start: "23:00",
      end: "23:30",
      repo: "flowd",
      branch: "main",
      focus: 29,
      switches: 25,
      ai: "Refactored flowd tracking with tmux window-name-as-category, cleaned install (zip download, no SSH), updated module path to mahi160/flowd. Heavy tool/git churn, light editor time — mostly scaffolding and config work.",
    },
    {
      start: "23:30",
      end: "00:00",
      repo: "flowd",
      branch: "main",
      focus: 28,
      switches: 4,
      ai: "Refactored flowd heavily — split `cli.go`, embedded dashboard HTML, added tests, net +413 lines. Mostly in editor/shell, minimal context switching despite 4 hops to other projects.",
    },
    {
      start: "00:00",
      end: "00:30",
      repo: "flowd",
      branch: "main",
      focus: 5,
      switches: 0,
    },
    {
      start: "06:00",
      end: "06:30",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "09:30",
      end: "10:00",
      repo: "flowd",
      branch: "main",
      focus: 4,
      switches: 0,
    },
    {
      start: "10:00",
      end: "10:30",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 39,
      switches: 2,
      ai: "Refactored 1 JS file in wick-ui on i18n-fixes branch — net code reduction (4 added, 8 removed). Mostly dev/editor split with minimal git work, low context switching.",
    },
    {
      start: "10:30",
      end: "11:00",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 60,
      switches: 28,
      ai: "i18n fixes on wick-ui: key stripping, ternary support, attribute translation, debug reporter, modularization — 5 commits, net +101 lines. Steady deep focus with high context switching (28 switches) across wick-ui and setthemacup.",
    },
    {
      start: "11:00",
      end: "11:30",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 59,
      switches: 28,
      ai: "Fixed i18n bugs in wick-ui: key propagation, ternary handling, newline stripping, attribute translation, and added build-time debug reporter (5 commits, 11 files, +177/−74). Heavy dev/editor split (29min/16min) with 28 context switches suggests iterative debug loop rather than planned feature work.",
    },
    {
      start: "11:30",
      end: "12:00",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 41,
      switches: 30,
      ai: "Fixed i18n key handling in wick-ui (newline stripping, ternary support, `data-i18n-key` propagation) with 11 files changed net-neutral. High context-switching (30 in 41 min) suggests iterative debugging rather than planned implementation.",
    },
    {
      start: "12:00",
      end: "12:30",
      repo: "setthemacup",
      branch: "main",
      focus: 12,
      switches: 8,
    },
    {
      start: "12:30",
      end: "13:00",
      repo: "setthemacup",
      branch: "main",
      focus: 44,
      switches: 8,
      ai: "Worked across two projects (setthemacup, wick-ui), net +122 lines across 12 files. Heavy node/dev tool usage suggests build/config work with frequent context switching (8 switches in 44 focused minutes).",
    },
    {
      start: "13:00",
      end: "13:30",
      repo: "setthemacup",
      branch: "main",
      focus: 55,
      switches: 6,
      ai: "Refactored across 2 projects (setthemacup + wick-ui), net +123 lines in 13 files. Heavy dev/node/Python tool split suggests frontend build work alongside scripting.",
    },
    {
      start: "13:30",
      end: "14:00",
      repo: "setthemacup",
      branch: "main",
      focus: 17,
      switches: 0,
      ai: "Built Python tooling for setthemacup repo, net-removing code (−61 lines). Zero context switches — deep focused session.",
    },
    {
      start: "14:00",
      end: "14:30",
      repo: "setthemacup",
      branch: "main",
      focus: 22,
      switches: 0,
      ai: "Session trimmed 61 lines, grew 40 — net cleanup. Single-repo Node work, zero context switches, stayed focused whole 30 min.",
    },
    {
      start: "14:30",
      end: "15:00",
      repo: "setthemacup",
      branch: "main",
      focus: 24,
      switches: 0,
      ai: "Refactored `setthemacup` repo: net line reduction (−21) across 7 files, Python-heavy work. Zero context switches = deep focused session.",
    },
    {
      start: "15:00",
      end: "15:30",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 15,
      switches: 0,
      ai: "Fixed i18n issues in wick-ui (key propagation, ternary handling), then cut 88 lines net-negative across 13 files. Tight session — zero context switches, mostly editor/dev work on one branch.",
    },
    {
      start: "15:30",
      end: "16:00",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 41,
      switches: 16,
      ai: "Fixed i18n bugs in wick-ui (branch `sifat-main-28apr-i18n-fixes`), net −17 lines across 7 files suggesting cleanup/simplification over new code. High context-switch count (16 in 41 min) points to iterative debugging rather than focused feature work.",
    },
    {
      start: "16:00",
      end: "16:30",
      repo: "setthemacup",
      branch: "main",
      focus: 50,
      switches: 10,
      ai: "Refactored `setthemacup` (44min primary focus), net deletion of 17 lines across 8 files — cleanup/consolidation work. Brief context-switching to `wick-ui` (7min) with TypeScript edits.",
    },
    {
      start: "16:30",
      end: "17:00",
      repo: "setthemacup",
      branch: "main",
      focus: 2,
      switches: 0,
    },
    {
      start: "17:00",
      end: "17:30",
      repo: "setthemacup",
      branch: "main",
      focus: 3,
      switches: 0,
    },
    {
      start: "17:30",
      end: "18:00",
      repo: "setthemacup",
      branch: "main",
      focus: 14,
      switches: 0,
    },
    {
      start: "18:00",
      end: "18:30",
      repo: "flowd",
      branch: "main",
      focus: 10,
      switches: 6,
    },
    {
      start: "20:30",
      end: "21:00",
      repo: "flowd",
      branch: "main",
      focus: 19,
      switches: 0,
      ai: "30min focused session on `flowd` repo, 0 context switches — added 12 lines, removed 3 across 2 files. Clean, uninterrupted dev work on main branch with no scope drift.",
    },
    {
      start: "21:00",
      end: "21:30",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 17,
      switches: 2,
      ai: "i18n fixes on wick-ui branch (11 min primary focus), net code reduction (−59 lines). Side context switches to setthemacup and flowd suggest multi-project maintenance session.",
    },
    {
      start: "21:30",
      end: "22:00",
      repo: "setthemacup",
      branch: "main",
      focus: 42,
      switches: 4,
      ai: "Fixed bugs and refactored in setthemacup (primary) with minor wick-ui work. Net negative lines (-17) suggests cleanup/simplification over new features.",
    },
    {
      start: "22:00",
      end: "22:30",
      repo: "setthemacup",
      branch: "main",
      focus: 4,
      switches: 0,
    },
    {
      start: "09:00",
      end: "09:30",
      repo: "wick-ui-v2",
      branch: "sifat-14jan-great-migration",
      focus: 5,
      switches: 0,
    },
    {
      start: "09:30",
      end: "10:00",
      repo: "flowd",
      branch: "main",
      focus: 25,
      switches: 0,
      ai: "Focused 25-min session on flowd (main branch), minimal context switching. Single file changed (+1 −1 lines) — likely small fix or config tweak.",
    },
    {
      start: "10:00",
      end: "10:30",
      repo: "flowd",
      branch: "main",
      focus: 18,
      switches: 1,
      ai: "Fixed i18n issues in wick-ui-v2 (bulk of time), minor work in flowd. Net +139 lines across 3 files, mostly additions with 1 context switch between repos.",
    },
    {
      start: "12:00",
      end: "12:30",
      repo: "wick-ui-v2",
      branch: "sifat-14jan-great-migration",
      focus: 11,
      switches: 1,
    },
    {
      start: "12:30",
      end: "13:00",
      repo: "setthemacup",
      branch: "main",
      focus: 27,
      switches: 4,
      ai: "Deleted 521 lines across 19 files, likely dead code/config cleanup. Heavy `bun` use suggests build/dep work; minimal context switches = focused session.",
    },
    {
      start: "13:00",
      end: "13:30",
      repo: "setthemacup",
      branch: "main",
      focus: 18,
      switches: 1,
      ai: "Built setup tooling or ran cleanup in `setthemacup` repo — net -476 lines across 19 files suggests heavy deletion/consolidation. Single context switch, bun-heavy workflow points to JS/TS scripting work.",
    },
    {
      start: "13:30",
      end: "14:00",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "14:00",
      end: "14:30",
      repo: "setthemacup",
      branch: "main",
      focus: 2,
      switches: 1,
    },
    {
      start: "14:30",
      end: "15:00",
      repo: "setthemacup",
      branch: "main",
      focus: 22,
      switches: 2,
      ai: "Deleted 521 lines across 19 files — heavy cleanup/removal session. Minimal new code (+45), suggesting dead code purge or dependency removal.",
    },
    {
      start: "15:00",
      end: "15:30",
      repo: "setthemacup",
      branch: "main",
      focus: 19,
      switches: 3,
      ai: "Fixed major cleanup in setthemacup (42 files, net −2438 lines). Likely removed legacy code or consolidated configs.",
    },
    {
      start: "15:30",
      end: "16:00",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "16:00",
      end: "16:30",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "16:30",
      end: "17:00",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "17:00",
      end: "17:30",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "17:30",
      end: "18:00",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "18:00",
      end: "18:30",
      repo: "setthemacup",
      branch: "main",
      focus: 4,
      switches: 0,
    },
    {
      start: "20:30",
      end: "21:00",
      repo: "setthemacup",
      branch: "main",
      focus: 18,
      switches: 0,
    },
    {
      start: "21:00",
      end: "21:30",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "21:30",
      end: "22:00",
      repo: "setthemacup",
      branch: "main",
      focus: 2,
      switches: 0,
    },
    {
      start: "22:00",
      end: "22:30",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "22:30",
      end: "23:00",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "23:00",
      end: "23:30",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "23:30",
      end: "00:00",
      repo: "pi-mono",
      branch: "calude-patch",
      focus: 10,
      switches: 0,
    },
    {
      start: "00:00",
      end: "00:30",
      repo: "pi-mono",
      branch: "calude-patch",
      focus: 18,
      switches: 0,
    },
    {
      start: "00:30",
      end: "01:00",
      repo: "setthemacup",
      branch: "main",
      focus: 25,
      switches: 0,
    },
    {
      start: "01:00",
      end: "01:30",
      repo: "setthemacup",
      branch: "main",
      focus: 23,
      switches: 0,
    },
    {
      start: "01:30",
      end: "02:00",
      repo: "setthemacup",
      branch: "main",
      focus: 29,
      switches: 0,
    },
    {
      start: "02:00",
      end: "02:30",
      repo: "setthemacup",
      branch: "main",
      focus: 16,
      switches: 0,
    },
    {
      start: "04:30",
      end: "05:00",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "05:30",
      end: "06:00",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "06:30",
      end: "07:00",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "09:30",
      end: "10:00",
      repo: "setthemacup",
      branch: "main",
      focus: 4,
      switches: 2,
    },
    {
      start: "10:00",
      end: "10:30",
      repo: "",
      branch: "",
      focus: 22,
      switches: 0,
    },
    {
      start: "10:30",
      end: "11:00",
      repo: "",
      branch: "",
      focus: 17,
      switches: 0,
    },
    {
      start: "11:00",
      end: "11:30",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 5,
      switches: 1,
    },
    {
      start: "11:30",
      end: "12:00",
      repo: "wick-ui",
      branch: "sifat-main-28apr-i18n-fixes",
      focus: 0,
      switches: 0,
    },
    {
      start: "12:00",
      end: "12:30",
      repo: "",
      branch: "",
      focus: 0,
      switches: 0,
    },
    {
      start: "12:30",
      end: "13:00",
      repo: "setthemacup",
      branch: "main",
      focus: 3,
      switches: 3,
    },
    {
      start: "18:15",
      end: "20:53",
      repo: "flowd",
      branch: "main",
      focus: 30,
      switches: 8,
    },
    {
      start: "20:53",
      end: "11:39",
      repo: "flowd",
      branch: "main-01may-refactor-ui",
      focus: 30,
      switches: 4,
      ai: "Migrated the `flowd` dashboard frontend from a monolithic setup to a Vite-based modular build pipeline, touching 50 files with significant churn (+12k/−7k lines). Primary tools were Neovim for editing and Node for building, with the work split across JavaScript, HTML, and CSS.",
    },
    {
      start: "11:39",
      end: "12:09",
      repo: "flowd",
      branch: "main-01may-refactor-ui",
      focus: 30,
      switches: 2,
      ai: "Spent 30 minutes refactoring the flowd dashboard UI — primarily CSS work with a large net addition (1132 lines added, 44 removed) across 6 files on the `main-01may-refactor-ui` branch. The session was focused and low-context-switch, suggesting sustained work on a single visual overhaul rather than exploratory debugging.",
    },
    {
      start: "12:09",
      end: "12:51",
      repo: "flowd",
      branch: "main-01may-refactor-ui",
      focus: 30,
      switches: 2,
      ai: "Refactored the flowd dashboard UI on the `main-01may-refactor-ui` branch, making minor edits to a single JavaScript file (+4/−1 lines). The session was focused with minimal context switching, primarily using Node and Neovim for a small, targeted change.",
    },
    {
      start: "12:51",
      end: "14:18",
      repo: "flowd",
      branch: "main",
      focus: 30,
      switches: 6,
      ai: "Refactored across 6 files with a net reduction of 4 lines, primarily in JavaScript with some TypeScript work in the flowd project. The session involved frequent context switching (6 switches) between editor, git, and terminal, suggesting iterative cleanup or bug-fixing work.",
    },
    {
      start: "14:18",
      end: "20:27",
      repo: "flowd",
      branch: "main",
      focus: 30,
      switches: 1,
    },
    {
      start: "20:27",
      end: "20:57",
      repo: "flowd",
      branch: "main-refactor-dashboard",
      focus: 30,
      switches: 1,
    },
    {
      start: "20:57",
      end: "21:27",
      repo: "flowd",
      branch: "main-refactor-dashboard",
      focus: 30,
      switches: 0,
    },
  ],
  streak_days: 5,
  top_repo: "setthemacup",
  top_branch: "main",
  ai_recap: "",
  ai_per_block: 28,
  machine: "workstation",
  os: "darwin",
};
